[package]
name = "features"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
default = ["feature_a"]
feature_a = []
feature_b = []
feature_c = []

# Empty workspace declaration as workaround for
# https://github.com/rust-lang/cargo/issues/14155
[workspace]
