[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"


[dependencies]
anyhow = "1.0.53"
assert_cmd = "2.0.4"
pretty_assertions = "1.3.0"
tempfile = "3.3.0"

[dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "*"
