[package]
edition = "2021"
name = "rustup-toolchain"
version = "0.1.6"
description = "Utilities for working with rustup toolchains, primarily from cargo test:s."
homepage = "https://github.com/Enselic/cargo-public-api/tree/main/rustup-toolchain"
documentation = "https://docs.rs/rustup-toolchain"
readme = "README.md"
keywords = ["toolchain", "rustup"]
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api/tree/main/rustup-toolchain"

[dependencies]
thiserror = "1.0.44"

[dev-dependencies]
expect-test = "1.5.0"

[dev-dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.9.0"

[dev-dependencies.public-api]
path = "../public-api"
version = "0.33.1"
